; --- Generated by HITCPU Compiler Backend ---

    movi r1, r5
    ; TODO: Unimplemented instruction op: 95
    str r1, "int"
.L_test_Function1:
    ; TODO: Unimplemented instruction op: 94
    ; TODO: Unimplemented instruction op: 91
    movi r2, r10
    add r3, r4, r2
    str r3, "int"
    ldr r5, "x"
    movi r6, r5
    bgt r5, r5, "THEN_0"
    jmp .L_ELSE_0:
.L_THEN_0:
    movi r7, r20
    str r7, "int"
    jmp .L_END_0:
.L_ELSE_0:
.L_END_0:
    addi r15, r15, r4
    ret.L_eight_parameter_test:
    addi r15, r15, r0
    ret.L_test_Function2:
    ; TODO: Unimplemented instruction op: 94
    ; TODO: Unimplemented instruction op: 91
    movi r8, r10
    add r9, r10, r8
    str r9, "int"
    ldr r11, "x"
    movi r12, r5
    bgt r11, r11, "THEN_1"
    jmp .L_ELSE_1:
.L_THEN_1:
    movi r13, r20
    str r13, "int"
    jmp .L_END_1:
.L_ELSE_1:
.L_END_1:
    addi r15, r15, r4
    ret.L_print:
    addi r15, r15, r0
    ret.L_main:
    ; TODO: Unimplemented instruction op: 92
    ; TODO: Unimplemented instruction op: 94
    STR r4, [r15 + 4] ; Spill vreg_2 to stack
    movi r4, r5
    str r4, "int"
    STR r6, [r15 + 12] ; Spill vreg_6 to stack
    movi r6, r4
    str r6, "t"
    STR r10, [r15 + 16] ; Spill vreg_8 to stack
    ldr r10, "x"
    STR r10, [r15 + 32] ; Spill vreg_16 to stack
    ldr r10, "y"
    STR r10, [r15 + 34] ; Spill vreg_17 to stack
    bgt r10, r10, "THEN_2"
    jmp .L_THEN_3:
.L_THEN_3:
    STR r12, [r15 + 24] ; Spill vreg_12 to stack
    ldr r12, "x"
    STR r12, [r15 + 36] ; Spill vreg_18 to stack
    ldr r12, "y"
    STR r12, [r15 + 38] ; Spill vreg_19 to stack
    bgt r12, r12, "THEN_2"
    jmp .L_ELSE_2:
.L_THEN_2:
    STR r1, [r15 + 0] ; Spill vreg_0 to stack
    ldr r1, "y"
    STR r1, [r15 + 40] ; Spill vreg_20 to stack
    ldr r1, "x"
    STR r1, [r15 + 42] ; Spill vreg_21 to stack
    bgt r1, r1, "THEN_4"
    jmp .L_ELSE_3:
.L_THEN_4:
    STR r1, [r15 + 40] ; Spill vreg_20 to stack
    ldr r1, "y"
    jmp .L_print:
    jmp .L_END_3:
.L_ELSE_3:
    STR r1, [r15 + 0] ; Spill vreg_0 to stack
    ldr r1, "x"
    STR r1, [r15 + 44] ; Spill vreg_22 to stack
    ldr r1, "y"
    STR r1, [r15 + 46] ; Spill vreg_23 to stack
    bgt r1, r1, "THEN_5"
    jmp .L_ELSE_4:
.L_THEN_5:
    STR r1, [r15 + 44] ; Spill vreg_22 to stack
    ldr r1, "x"
    jmp .L_print:
    jmp .L_END_4:
.L_ELSE_4:
.L_END_4:
.L_END_3:
    jmp .L_END_2:
.L_ELSE_2:
    STR r1, [r15 + 0] ; Spill vreg_0 to stack
    ldr r1, "y"
    STR r1, [r15 + 48] ; Spill vreg_24 to stack
    ldr r1, "x"
    STR r1, [r15 + 50] ; Spill vreg_25 to stack
    bgt r1, r1, "THEN_6"
    jmp .L_ELSE_5:
.L_THEN_6:
    STR r1, [r15 + 48] ; Spill vreg_24 to stack
    ldr r1, "y"
    jmp .L_print:
    jmp .L_END_5:
.L_ELSE_5:
    STR r1, [r15 + 0] ; Spill vreg_0 to stack
    ldr r1, "x"
    STR r1, [r15 + 52] ; Spill vreg_26 to stack
    ldr r1, "y"
    STR r1, [r15 + 54] ; Spill vreg_27 to stack
    bgt r1, r1, "THEN_7"
    jmp .L_ELSE_6:
.L_THEN_7:
    STR r1, [r15 + 52] ; Spill vreg_26 to stack
    ldr r1, "x"
    jmp .L_print:
    jmp .L_END_6:
.L_ELSE_6:
.L_END_6:
.L_END_5:
.L_END_2:
    ldr r1, "global"
    jmp .L_test_Function1:
    movi r1, r1
    STR r2, [r15 + 6] ; Spill vreg_3 to stack
    movi r2, r2
    STR r2, [r15 + 2] ; Spill vreg_1 to stack
    movi r2, r3
    STR r2, [r15 + 4] ; Spill vreg_2 to stack
    movi r2, r4
    movi r3, r5
    movi r5, r6
    STR r2, [r15 + 6] ; Spill vreg_3 to stack
    movi r2, r7
    movi r7, r8
    ; TODO: Unimplemented instruction op: 92
    jmp .L_eight_parameter_test:
    ldr r1, "global"
    jmp .L_test_Function2:
    addi r15, r15, r6
    ret