; --- Generated by HITCPU Compiler Backend ---

    movi r1, r5
    str r1, "global"
.L_test_Function1:
    subi r15, r15, r4
    str r1, "apple"
    str r2, "x"
    ldr r3, "x"
    movi r4, r5
    bgt r3, r3, "THEN_0"
    jmp .L_ELSE_0:
.L_THEN_0:
    movi r5, r20
    str r5, "y"
    jmp .L_END_0:
.L_ELSE_0:
.L_END_0:
    addi r15, r15, r4
    ret.L_eight_parameter_test:
    subi r15, r15, r16
    str r1, "one"
    str r3, "two"
    str r4, "three"
    str r5, "four"
    str r6, "five"
    str r7, "six"
    str r8, "seven"
    addi r15, r15, r16
    ret.L_test_Function2:
    subi r15, r15, r4
    str r1, "apple"
    str r2, "x"
    ldr r6, "x"
    movi r7, r5
    bgt r6, r6, "THEN_1"
    jmp .L_ELSE_1:
.L_THEN_1:
    movi r8, r20
    str r8, "y"
    jmp .L_END_1:
.L_ELSE_1:
.L_END_1:
    addi r15, r15, r4
    ret.L_print:
    subi r15, r15, r2
    str r1, "print"
    addi r15, r15, r2
    ret.L_main:
    subi r15, r15, r4
    movi r9, r5
    str r9, "x"
    movi r10, r4
    str r10, "y"
    ldr r11, "x"
    ldr r12, "y"
    bgt r11, r11, "THEN_2"
    jmp .L_THEN_3:
.L_THEN_3:
    ldr r13, "x"
    STR r12, [r15 + 20] ; Spill vreg_10 to stack
    ldr r12, "y"
    bgt r13, r13, "THEN_2"
    jmp .L_ELSE_2:
.L_THEN_2:
    STR r12, [r15 + 24] ; Spill vreg_12 to stack
    ldr r12, "y"
    STR r12, [r15 + 26] ; Spill vreg_13 to stack
    ldr r12, "x"
    STR r12, [r15 + 28] ; Spill vreg_14 to stack
    bgt r12, r12, "THEN_4"
    jmp .L_ELSE_3:
.L_THEN_4:
    ldr r1, "y"
    jmp .L_print:
    jmp .L_END_3:
.L_ELSE_3:
    STR r2, [r15 + -2] ; Spill vreg_-1 to stack
    ldr r2, "x"
    STR r2, [r15 + 30] ; Spill vreg_15 to stack
    ldr r2, "y"
    STR r2, [r15 + 32] ; Spill vreg_16 to stack
    bgt r2, r2, "THEN_5"
    jmp .L_ELSE_4:
.L_THEN_5:
    ldr r1, "x"
    jmp .L_print:
    jmp .L_END_4:
.L_ELSE_4:
.L_END_4:
.L_END_3:
    jmp .L_END_2:
.L_ELSE_2:
    STR r2, [r15 + 30] ; Spill vreg_15 to stack
    ldr r2, "y"
    STR r2, [r15 + 34] ; Spill vreg_17 to stack
    ldr r2, "x"
    STR r2, [r15 + 36] ; Spill vreg_18 to stack
    bgt r2, r2, "THEN_6"
    jmp .L_ELSE_5:
.L_THEN_6:
    ldr r1, "y"
    jmp .L_print:
    jmp .L_END_5:
.L_ELSE_5:
    STR r2, [r15 + 34] ; Spill vreg_17 to stack
    ldr r2, "x"
    STR r2, [r15 + 38] ; Spill vreg_19 to stack
    ldr r2, "y"
    STR r2, [r15 + 40] ; Spill vreg_20 to stack
    bgt r2, r2, "THEN_7"
    jmp .L_ELSE_6:
.L_THEN_7:
    ldr r1, "x"
    jmp .L_print:
    jmp .L_END_6:
.L_ELSE_6:
.L_END_6:
.L_END_5:
.L_END_2:
    ldr r1, "global"
    jmp .L_test_Function1:
    movi r1, r1
    movi r3, r2
    movi r4, r3
    movi r5, r4
    movi r6, r5
    movi r7, r6
    movi r8, r7
    movi r9, r8
    ; ERROR: String pool offset 1015 out of bounds!
    jmp .L_eight_parameter_test:
    ldr r1, "global"
    jmp .L_test_Function2:
    addi r15, r15, r4
    ret