#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "struct.h"

int allocate_register(int vreg_id, FILE *out, RegStatus *reg_status) {
    // check if reg is stack pointer
    if (vreg_id == VREG_R15) return 15;

    // check if reg is ret address
    if (vreg_id == VREG_R14) return 14;

    // check if reg is zero reg
    if (vreg_id == VREG_R0) return 0;

    // Check if v_reg is in a reg already
    for (int i = 0; i < 13; i++) {
        if (reg_status->reg[i].is_busy && reg_status->reg[i].vreg_id == vreg_id) {
            reg_status->reg[i].least_used++;
            return i + 1;
        }
    }

    // Check for empty regs
    for (int i = 0; i < 13; i++) {
        if (!reg_status->reg[i].is_busy) {
            reg_status->reg[i].is_busy = 1;
            reg_status->reg[i].least_used = 1;
            reg_status->reg[i].vreg_id = vreg_id;
            return i + 1;
        }
    }
    
    // Spill register into stack when full
    int victim_reg = 0;
    int best = reg_status->reg[0].least_used;

    for (int i = 1; i < 13; i++) {
        if (reg_status->reg[i].least_used < best) {
            best = reg_status->reg[i].least_used;
            victim_reg = i;
        }
    }

    int victim_vreg = reg_status->reg[victim_reg].vreg_id;
    // For now it's 4 but this should be depeding on the type no?
    // For 16 bit arhc, int is 2 bytes, char is 1 byte.. I think
    int bytes_per_reg = 2;
    int stack_offset = victim_vreg * bytes_per_reg;

    fprintf(out, "    STR r%d, [r15 + %d] ; Spill vreg_%d to stack\n", 
            victim_reg + 1, stack_offset, victim_vreg);

    reg_status->reg[victim_reg].vreg_id = vreg_id;
    reg_status->reg[victim_reg].least_used = 1;

    return victim_reg + 1;
}

void hitcpu_emit_assembly(const char *output_filename, InstructionStream *stream, StringPool *pool, RegStatus *reg_status) {
    FILE *out = fopen(output_filename, "w");
    if (!out) {
        perror("Failed to open target assembly output file");
        return;
    }

    fprintf(out, "; --- Generated by HITCPU Compiler Backend ---\n\n");

    for (int i = 0; i < stream->count; i++) {
        AsmInstruction inst = stream->data[i];
        
        switch (inst.op) {
            case OP_LABEL: {
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, ".L_%s:\n", string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }
            
            case OP_JMP: { // <-- Added braces
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    jmp .L_%s:\n", string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }

            case OP_ADD:
                // Translate virtual registers to your targeted HITCPU registers
                fprintf(out, "    add r%d, r%d, r%d\n", allocate_register(inst.dest, out, reg_status), allocate_register(inst.src1, out, reg_status), allocate_register(inst.src2_or_imm.src2, out, reg_status));
                break;
                
            case OP_ADDI:
                fprintf(out, "    addi r%d, r%d, r%d\n", allocate_register(inst.dest, out, reg_status), allocate_register(inst.src1, out, reg_status), inst.src2_or_imm.imm);
                break;
                
            case OP_SUBI:
                // Translate virtual registers to your targeted HITCPU registers
                fprintf(out, "    subi r%d, r%d, r%d\n", allocate_register(inst.dest, out, reg_status), allocate_register(inst.src1, out, reg_status), inst.src2_or_imm.imm);
                break;
            
            case OP_MOVI:
                fprintf(out, "    movi r%d, r%d\n", allocate_register(inst.dest, out, reg_status), inst.src2_or_imm.imm);
                break;

            case OP_BEQ: { // <-- Added braces
                int r_dest = allocate_register(inst.dest, out, reg_status);
                int r_src1 = allocate_register(inst.dest, out, reg_status);
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    bgt r%d, r%d, \"%s\"\n", r_dest, r_src1, string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }

            case OP_BGT: { // <-- Added braces
                int r_dest = allocate_register(inst.dest, out, reg_status);
                int r_src1 = allocate_register(inst.dest, out, reg_status);
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    bgt r%d, r%d, \"%s\"\n", r_dest, r_src1, string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }

            case OP_STR: { // <-- Added braces
                int r_dest = allocate_register(inst.dest, out, reg_status);
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    str r%d, \"%s\"\n", r_dest, string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }
            
            case OP_LDR: { // <-- Added braces
                int r_dest = allocate_register(inst.dest, out, reg_status);
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    ldr r%d, \"%s\"\n", r_dest, string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }
                
            case OP_CALL: { // <-- Added braces
                int offset = inst.src2_or_imm.offset;
                if (offset >= 0 && offset < pool->size) {
                    const char *string_literal = &pool->data[offset]; 
                    fprintf(out, "    jmp .L_%s:\n", string_literal);
                } else {
                    fprintf(out, "    ; ERROR: String pool offset %d out of bounds!\n", offset);
                }
                break;
            }
                
            case OP_RET:
                fprintf(out, "    ret");
                break;

            default:
                // Handle or log unhandled instructions so your compiler doesn't silently ignore them
                fprintf(out, "    ; TODO: Unimplemented instruction op: %d\n", inst.op);
                break;
        }
    }

    fclose(out);
    printf("Successfully compiled HITCPU assembly: %s\n", output_filename);
}